### ISSUE TITLE
episodes.xml seems to be broken: ERROR: rtmp server sent error

### ISSUE THREAD

**Issue by cbpygit** [craue/SouthParkDownloader#1]
When trying to run the SouthParkDownloader on Windows 10 using the provided tool collection, different errors occur (even on the same command). Using the test case from README.md, I get

    >> php download.php s=13 e=8 l=de+en

    RTMPDump v2.4
    (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
    Connecting ...
    WARNING: HandShake: Type mismatch: client sent 6, server answered 8
    INFO: Connected...
    ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!
    ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!
    ...
    ERROR: HandleInvoke, error decoding invoke packet
    ERROR: RTMP_ReadPacket, failed to read RTMP packet body. len: 4390912
    External program aborted with an exit code of "1" which seems to be an error. Will abort now.

On the second try, I get a different error:

    RTMPDump v2.4
    (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
    Connecting ...
    WARNING: HandShake: Type mismatch: client sent 6, server answered 8
    INFO: Connected...
    ERROR: rtmp server sent error
    ERROR: rtmp server requested close
    External program aborted with an exit code of "1" which seems to be an error. Will abort now.

A fix and a more complete episodes.xml would be greatly appreciated.

**Comment by craue** [comment]
Try the latest release now. 😏
