### ISSUE TITLE
Episoed always english or german

### ISSUE THREAD

**Issue by WeWin55** [craue/SouthParkDownloader#12]
HI,

first of all thanks for your nice project!

My Problem:

I want to have the episodes in german as main language and english as second. But every country (vpn) i tried its always english (both soundtracks,l=de+en) or german (de, at, ch).

Ive tested it with this command:
php download.php s=13 e=8 l=de+en

Do you know any workaround?
Thanks.

**Comment by craue** [comment]
Can you try again with the latest code? It should be fixed by 3b6bdac650bfa2bde3239929b150021f0748ae77, refs #15.
