### ISSUE TITLE
Everything is always in English

### ISSUE THREAD

**Issue by ark626** [craue/SouthParkDownloader#15]
Trying to download the German Dub results in also getting simply English.
de + en or de doesnt work as the result is either 2 times english or 1 times english in the audio.
Altough the country code is proper, the audio isnt

**Comment by craue** [comment]
The cause is most probably geo-blocking so you'll need to use a VPN.

**Comment by ark626** [comment]
@craue  i dont think so, i have a german ip and can watch them from the original site in the correct language. So it shouldnt be the issue

**Comment by craue** [comment]
Confirmed, but there's nothing I can do about it right now. Will check that in the next weeks...

**Comment by rizzodieratte** [comment]
I am having the same issue. 
php download.php s=18 e=7 l=de or php download.php s=18 e=7 l=de+en makes no difference.

**Comment by craue** [comment]
This should be working (again) with the latest commit. Can you confirm?

Unfortunately, it seems that all checksums have changed, so you could just switch off the verification for now or even better, help updating the database.
