### ISSUE TITLE
Failed to open stream

### ISSUE THREAD

**Issue by ghost** [craue/SouthParkDownloader#16]
`Warning: require(*\SouthParkDownloader-20170429/vendor/autoload.php): failed to open stream: No such file or directory in *\SouthParkDownloader-20170429\download.php on line 13`

There is no file autoload.php in the vendor directory of the newest release.

`php -r "eval('?>'.file_get_contents('http://getcomposer.org/installer'));" -- --install-dir=vendor php vendor/composer.phar --no-interaction --no-plugins install --prefer-dist`

This command only adds a file called "composer.phar" to the vendor folder.

**Comment by craue** [comment]
Be aware that there are actually two commands, not just one.
