### ISSUE TITLE
Having this error on Linux - Debian based one.

### ISSUE THREAD

**Issue by Monomol** [craue/SouthParkDownloader#17]
`fetching available seasons
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /root/Desktop/SP/SouthParkDownloader-master/app/SouthParkDownloader.php:646
Stack trace:
#0 /root/Desktop/SP/SouthParkDownloader-master/app/SouthParkDownloader.php(72): SouthParkDownloader->getAvailableSeasons('en')
#1 /root/Desktop/SP/SouthParkDownloader-master/download.php(34): SouthParkDownloader->run()
#2 {main}
  thrown in /root/Desktop/SP/SouthParkDownloader-master/app/SouthParkDownloader.php on line 646
`

**Comment by Monomol** [comment]
Also (i have another one working on windows) S21E03 isn't downloadable atm - Failed fetching episode metadata.

**Comment by jt0in3e** [comment]
same error for me as well

**Comment by craue** [comment]
It seems like you need to add the [DOM extension](http://php.net/manual/en/book.dom.php) to your PHP installation.

I've added ext-dom as a requirement.
