### ISSUE TITLE
Problem fetching available seasons

### ISSUE THREAD

**Issue by CHJ85** [craue/SouthParkDownloader#21]
Seeing this error while trying to fetch available seasons
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /home/chris/SouthParkDownloader/app/SouthParkDownloader.php:640
Stack trace:
#0 /home/chris/SouthParkDownloader/app/SouthParkDownloader.php(72): SouthParkDownloader->getAvailableSeasons('en')
#1 /home/chris/SouthParkDownloader/download.php(33): SouthParkDownloader->run()
#2 {main}
  thrown in /home/chris/SouthParkDownloader/app/SouthParkDownloader.php on line 640

**Comment by craue** [comment]
see #17
