### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by scotrod** [craue/SouthParkDownloader#22]
Hey, sorry that I'm too dump with PHP but I cannot install the script, when I type in `php -r "eval('?>'.file_get_contents('http://getcomposer.org/installer'));" -- --install-dir=vendor` I get error from PHP saying "The defined install dir (vendor) does not exist."
How can I resolve this?
Thanks!

**Comment by craue** [comment]
Oh, true. I've updated the installation instructions.
