### ISSUE TITLE
Fetching Season without any response

### ISSUE THREAD

**Issue by K33pSm1l1ng** [craue/SouthParkDownloader#4]
Hi, after execute the command e.g.:  "php download.php s=13 l=de"
I'm getting this output on command line: 
_fetching available seasons
fetching episodes for S13DE_

Nothing else happend after the command was executed...
After that, I've tried the following cmd: "php download.php s=13 e=8 l=de"
then I'm getting this ouput: 

_Fatal error: Uncaught Error: Call to a member function getSeason() on null in D:\Southpark_DL\app\SouthParkDownloader.php:74
Stack trace:
#0 D:\Southpark_DL\download.php(34): SouthParkDownloader->run()
#1 {main}
  thrown in D:\Southpark_DL\app\SouthParkDownloader.php on line 74_

**Comment by craue** [comment]
The official website seems to be broken (it states "-1 episodes" for several seasons), so try again when this has been fixed.

**Comment by K33pSm1l1ng** [comment]
Ah ok, I thought it's an other problem. Thanks for the update.
