### ISSUE TITLE
Failed to set value '-i' for option 'hide_banner'

### ISSUE THREAD

**Issue by shadow-storage** [craue/SouthParkDownloader#7]
root@server03:~/SouthPark/SouthParkDownloader# php download.php s=1 l=de+en
fetching available seasons
fetching episodes for S01DE
fetching episodes for S01EN
processing S01E01
  fetching episode metadata for S01E01
  fetching act metadata for S01E01A1DE
  will download S01E01A1DE to /tmp/S01E01A1DE.mp4
  fetching act metadata for S01E01A1EN
  will download S01E01A1EN to /tmp/S01E01A1EN.mp4
  fetching act metadata for S01E01A2DE
  will download S01E01A2DE to /tmp/S01E01A2DE.mp4
  fetching act metadata for S01E01A2EN
  will download S01E01A2EN to /tmp/S01E01A2EN.mp4
  fetching act metadata for S01E01A3DE
  will download S01E01A3DE to /tmp/S01E01A3DE.mp4
  fetching act metadata for S01E01A3EN
  will download S01E01A3EN to /tmp/S01E01A3EN.mp4
  fetching act metadata for S01E01A4DE
  will download S01E01A4DE to /tmp/S01E01A4DE.mp4
  fetching act metadata for S01E01A4EN
  will download S01E01A4EN to /tmp/S01E01A4EN.mp4
  starting 8 parallel downloads
  > /usr/bin/ffmpeg -hide_banner -i https://cp541867-vh.akamaihd.net/i/mtvnorigin/gsp.comedystor/com/sp/season-1/0101                 /acts/sp_0101_actHD_01_B_,480x360_300,480x360_400,640x480_600,640x480_800,.mp4.csmil/master.m3u8\?hdnea=st%3D15098434                 68%7Eexp%3D1509857868%7Eacl%3D%2Fi%2Fmtvnorigin%2Fgsp.comedystor%2Fcom%2Fsp%2Fseason-1%2F0101%2Facts%2Fsp_0101_actHD_                 01_B_%2C480x360_300%2C480x360_400%2C640x480_600%2C640x480_800%2C.mp4.csmil%2F\*%7Ehmac%3Dcc7f50afae9276a134566f2d71bd                 950a5ff011da066fe8bafbfe6c6bd1d1de96\&__a__=off\&__b__=10000\&__viacc__=NONE -codec copy '/tmp/S01E01A1DE.mp4'
  > /usr/bin/ffmpeg -hide_banner -i https://cp541867-vh.akamaihd.net/i/mtvnorigin/gsp.comedystor/com/sp/season-1/0101                 /acts/sp_0101_actHD_01_B_,480x360_300,480x360_400,640x480_600,640x480_800,.mp4.csmil/master.m3u8\?hdnea=st%3D15098434                 68%7Eexp%3D1509857868%7Eacl%3D%2Fi%2Fmtvnorigin%2Fgsp.comedystor%2Fcom%2Fsp%2Fseason-1%2F0101%2Facts%2Fsp_0101_actHD_                 01_B_%2C480x360_300%2C480x360_400%2C640x480_600%2C640x480_800%2C.mp4.csmil%2F\*%7Ehmac%3Dcc7f50afae9276a134566f2d71bd                 950a5ff011da066fe8bafbfe6c6bd1d1de96\&__a__=off\&__b__=10000\&__viacc__=NONE -codec copy '/tmp/S01E01A1EN.mp4'
  > /usr/bin/ffmpeg -hide_banner -i https://cp541867-vh.akamaihd.net/i/mtvnorigin/gsp.comedystor/com/sp/season-1/0101                 /acts/sp_0101_actHD_02_B_,480x360_300,480x360_400,640x480_600,640x480_800,.mp4.csmil/master.m3u8\?hdnea=st%3D15098434                 68%7Eexp%3D1509857868%7Eacl%3D%2Fi%2Fmtvnorigin%2Fgsp.comedystor%2Fcom%2Fsp%2Fseason-1%2F0101%2Facts%2Fsp_0101_actHD_                 02_B_%2C480x360_300%2C480x360_400%2C640x480_600%2C640x480_800%2C.mp4.csmil%2F\*%7Ehmac%3D7a9c67f5eedb8dd9a0d50046efed                 df29fdca25f4e7bcaac3d285e4241545035b\&__a__=off\&__b__=10000\&__viacc__=NONE -codec copy '/tmp/S01E01A2DE.mp4'
  > /usr/bin/ffmpeg -hide_banner -i https://cp541867-vh.akamaihd.net/i/mtvnorigin/gsp.comedystor/com/sp/season-1/0101                 /acts/sp_0101_actHD_02_B_,480x360_300,480x360_400,640x480_600,640x480_800,.mp4.csmil/master.m3u8\?hdnea=st%3D15098434                 68%7Eexp%3D1509857868%7Eacl%3D%2Fi%2Fmtvnorigin%2Fgsp.comedystor%2Fcom%2Fsp%2Fseason-1%2F0101%2Facts%2Fsp_0101_actHD_                 02_B_%2C480x360_300%2C480x360_400%2C640x480_600%2C640x480_800%2C.mp4.csmil%2F\*%7Ehmac%3D7a9c67f5eedb8dd9a0d50046efed                 df29fdca25f4e7bcaac3d285e4241545035b\&__a__=off\&__b__=10000\&__viacc__=NONE -codec copy '/tmp/S01E01A2EN.mp4'
  > /usr/bin/ffmpeg -hide_banner -i https://cp541867-vh.akamaihd.net/i/mtvnorigin/gsp.comedystor/com/sp/season-1/0101                 /acts/sp_0101_actHD_03_B_,480x360_300,480x360_400,640x480_600,640x480_800,.mp4.csmil/master.m3u8\?hdnea=st%3D15098434                 69%7Eexp%3D1509857869%7Eacl%3D%2Fi%2Fmtvnorigin%2Fgsp.comedystor%2Fcom%2Fsp%2Fseason-1%2F0101%2Facts%2Fsp_0101_actHD_                 03_B_%2C480x360_300%2C480x360_400%2C640x480_600%2C640x480_800%2C.mp4.csmil%2F\*%7Ehmac%3D44baf23c7bc81b5dcf9ef79b8237                 b7b57d89cc5e0dc33a08444c28264aba38c6\&__a__=off\&__b__=10000\&__viacc__=NONE -codec copy '/tmp/S01E01A3DE.mp4'
  > /usr/bin/ffmpeg -hide_banner -i https://cp541867-vh.akamaihd.net/i/mtvnorigin/gsp.comedystor/com/sp/season-1/0101                 /acts/sp_0101_actHD_03_B_,480x360_300,480x360_400,640x480_600,640x480_800,.mp4.csmil/master.m3u8\?hdnea=st%3D15098434                 69%7Eexp%3D1509857869%7Eacl%3D%2Fi%2Fmtvnorigin%2Fgsp.comedystor%2Fcom%2Fsp%2Fseason-1%2F0101%2Facts%2Fsp_0101_actHD_                 03_B_%2C480x360_300%2C480x360_400%2C640x480_600%2C640x480_800%2C.mp4.csmil%2F\*%7Ehmac%3D44baf23c7bc81b5dcf9ef79b8237                 b7b57d89cc5e0dc33a08444c28264aba38c6\&__a__=off\&__b__=10000\&__viacc__=NONE -codec copy '/tmp/S01E01A3EN.mp4'
  > /usr/bin/ffmpeg -hide_banner -i https://cp541867-vh.akamaihd.net/i/mtvnorigin/gsp.comedystor/com/sp/season-1/0101                 /acts/sp_0101_actHD_04_B_,480x360_300,480x360_400,640x480_600,640x480_800,.mp4.csmil/master.m3u8\?hdnea=st%3D15098434                 69%7Eexp%3D1509857869%7Eacl%3D%2Fi%2Fmtvnorigin%2Fgsp.comedystor%2Fcom%2Fsp%2Fseason-1%2F0101%2Facts%2Fsp_0101_actHD_                 04_B_%2C480x360_300%2C480x360_400%2C640x480_600%2C640x480_800%2C.mp4.csmil%2F\*%7Ehmac%3D9b54309965c016f6e5f13d6bdf52                 f31942e744b0fe1b1db8921fe6f6b8b62acb\&__a__=off\&__b__=10000\&__viacc__=NONE -codec copy '/tmp/S01E01A4DE.mp4'
  > /usr/bin/ffmpeg -hide_banner -i https://cp541867-vh.akamaihd.net/i/mtvnorigin/gsp.comedystor/com/sp/season-1/0101                 /acts/sp_0101_actHD_04_B_,480x360_300,480x360_400,640x480_600,640x480_800,.mp4.csmil/master.m3u8\?hdnea=st%3D15098434                 69%7Eexp%3D1509857869%7Eacl%3D%2Fi%2Fmtvnorigin%2Fgsp.comedystor%2Fcom%2Fsp%2Fseason-1%2F0101%2Facts%2Fsp_0101_actHD_                 04_B_%2C480x360_300%2C480x360_400%2C640x480_600%2C640x480_800%2C.mp4.csmil%2F\*%7Ehmac%3D9b54309965c016f6e5f13d6bdf52                 f31942e744b0fe1b1db8921fe6f6b8b62acb\&__a__=off\&__b__=10000\&__viacc__=NONE -codec copy '/tmp/S01E01A4EN.mp4'
ffmpeg version 0.8.21-6:0.8.21-0+deb7u1, Copyright (c) 2000-2014 the Libav developers
  built on Oct 16 2017 15:36:54 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'hide_banner'
Failed to set value '-i' for option 'hide_banner'
External program aborted with an exit code of "1" which seems to be an error. Will abort now.ffmpeg version 0.8.21-6:                 0.8.21-0+deb7u1, Copyright (c) 2000-2014 the Libav developers
  built on Oct 16 2017 15:36:54 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'hide_banner'
Failed to set value '-i' for option 'hide_banner'
ffmpeg version 0.8.21-6:0.8.21-0+deb7u1, Copyright (c) 2000-2014 the Libav developers
  built on Oct 16 2017 15:36:54 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'hide_banner'
Failed to set value '-i' for option 'hide_banner'
ffmpeg version 0.8.21-6:0.8.21-0+deb7u1, Copyright (c) 2000-2014 the Libav developers
  built on Oct 16 2017 15:36:54 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'hide_banner'
Failed to set value '-i' for option 'hide_banner'
ffmpeg version 0.8.21-6:0.8.21-0+deb7u1, Copyright (c) 2000-2014 the Libav developers
  built on Oct 16 2017 15:36:54 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'hide_banner'
Failed to set value '-i' for option 'hide_banner'
ffmpeg version 0.8.21-6:0.8.21-0+deb7u1, Copyright (c) 2000-2014 the Libav developers
  built on Oct 16 2017 15:36:54 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'hide_banner'
Failed to set value '-i' for option 'hide_banner'
ffmpeg version 0.8.21-6:0.8.21-0+deb7u1, Copyright (c) 2000-2014 the Libav developers
  built on Oct 16 2017 15:36:54 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'hide_banner'
Failed to set value '-i' for option 'hide_banner'
ffmpeg version 0.8.21-6:0.8.21-0+deb7u1, Copyright (c) 2000-2014 the Libav developers
  built on Oct 16 2017 15:36:54 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'hide_banner'
Failed to set value '-i' for option 'hide_banner'

**Comment by craue** [comment]
This should be fixed now.
